name: secrets and Variables

on:
  workflow_dispatch:

jobs:
  staging-environment:
    runs-on: ubuntu-24.04
    environment: MY_NAME
    env:
      # Inject repository-level secret & variable into the shell
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.OK }}
      EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.OK }}
      # Inject environment-level items into the shell
      EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.PROFILE_NAME }}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.PROFILES_NAME }}
    steps:
      - name: Inspect values inside job
        run: |
          echo "Repo secret (masked):    $PROFILE_NAME"
          echo "Repo variable:           $EXAMPLE_REPOSITORY_VARIABLE"
          echo "Env secret (masked):     $EXAMPLE_ENVIRONMENT_SECRET"
          echo "Env variable:            $EXAMPLE_ENVIRONMENT_VARIABLE"

  # production-environment:
  #   runs-on: ubuntu-24.04
  #   environment: MY_NAME
  #   env:
  #     # Inject repository-level secret & variable into the shell
  #     EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
  #     EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.EXAMPLE_REPOSITORY_VARIABLE }}
  #     # Inject environment-level items into the shell
  #     EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
  #     EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE }}
  #   steps:
  #     - name: Inspect values inside job
  #       run: |
  #         echo "Repo secret (masked):    $EXAMPLE_REPOSITORY_SECRET"
  #         echo "Repo variable:           $EXAMPLE_REPOSITORY_VARIABLE"
  #         echo "Env secret (masked):     $EXAMPLE_ENVIRONMENT_SECRET"
  #         echo "Env variable:            $EXAMPLE_ENVIRONMENT_VARIABLE"
