name: Print Hello in Python

on:
  workflow_dispatch:

jobs:
  Python-Hello:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run python program
        run: python hello.py
